Gmlu.Demo.Web/Controllers/RaspberryController.cs
using Gmlu.Demo.EntityFramework.DataContext;
using Gmlu.Demo.EntityFramework.Models;
using Gmlu.Demo.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Gmlu.Demo.Web.Controllers
{
    public class RaspberryController : Controller
    {
        private readonly StatsContext _context;

        public RaspberryController(
            StatsContext context)
        {
            _context = context;
        }


        // GET: RaspberryController
        public ActionResult Index()
        {
            return View(_context.Raspberrys);
        }


        // GET: RaspberryController/Create
        public ActionResult Create()
        {
            var viewModel = new RaspberryCreateViewModel();
            return View(viewModel);
        }

        // POST: RaspberryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RaspberryCreateViewModel newModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", newModel);
            }

            try
            {
                var newEntity = new Raspberry();
                newEntity.Name = newModel.Name;
                newEntity.location = newModel.Location;
                newEntity.IPadress = newModel.IPadress;
                newEntity.RaspberryId = Guid.NewGuid();
                _context.Raspberrys.Add(newEntity);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Create", newModel);
            }
        }


        // GET: RaspberryController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var entity = _context.Raspberrys.Find(id);
            RaspberryEditViewModel viewModel = new RaspberryEditViewModel()
            {
                RaspberryId = entity.RaspberryId,
                IPadress = entity.IPadress,
                Location = entity.location,
                Name = entity.Name
            };
            return View(viewModel);
        }

        // POST: RaspberryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveRaspberryChange(RaspberryEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            var entity = _context
                .Raspberrys
                .Find(
                    model.RaspberryId);

            entity.Name = model.Name;
            entity.location = model.Location;
            entity.IPadress = model.IPadress;

            _context.Raspberrys.Update(entity);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        // GET: RaspberryController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var entity = _context.Raspberrys.Find(id);
            RaspberryEditViewModel viewModel = new RaspberryEditViewModel()
            {
                RaspberryId = entity.RaspberryId,
                IPadress = entity.IPadress,
                Location = entity.location,
                Name = entity.Name
            };

            return View(viewModel);
        }

        // POST: RaspberryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRaspberry(IFormCollection form)
        {
            try
            {
                Guid id = Guid.Parse(form["RaspberryId"]);
                var entity = _context.Raspberrys.Find(id);
                _context.Raspberrys.Remove(entity);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Gmlu.Demo.Web/Views/Raspberry/Create.cshtml
@model RaspberryCreateViewModel

<form asp-controller="Raspberry" asp-action="Create" method="post">
    <div class="form-group">



        <label for="Location"><Br />Location</label>
        <input type="text" class="form-control" id="Location" asp-for="Location" />
        <label for="Name"><Br />Name</label>
        <input type="text" class="form-control" id="Name" asp-for="Name" />
        <label for="Ipadress"><Br />Ip Adress</label>
        <input type="text" class="form-control" id="IPadress" asp-for="IPadress" />


    </div>

    <button type="submit" class="btn btn-success">Create</button>

    <div asp-validation-summary="All" class="text-danger"></div>

    <form class="m-1 p-1" method="post">
    </form>

    <style>
        .input-validation-error {
            border-color: red;
        }
    </style>
</form>

Gmlu.Demo.Web/Views/Raspberry/Delete.cshtml
@model RaspberryEditViewModel

<form asp-controller="Raspberry" asp-action="DeleteRaspberry" method="post">
    <div class="form-group">

        <h2>Delete Object:<br /></h2>
        <label for="RaspberryId"><Br />Raspberry ID</label>
        <input type="hidden" class="form-control" id="RaspberryId" asp-for="RaspberryId" />
        <label for="Location"><Br />Location</label>
        <input type="text" disabled class="form-control" id="Location" asp-for="Location" />
        <label for="Name"><Br />Name</label>
        <input type="text" disabled class="form-control" id="Name" asp-for="Name" />
        <label for="IPadress"><Br />Ip Adress</label>
        <input type="text" disabled class="form-control" id="IPadress" asp-for="IPadress" />


    </div>

    <button type="submit" class="btn btn-danger">Delete</button>
    
</form>

Gmlu.Demo.Web/Views/Raspberry/Edit.cshtml
@model RaspberryEditViewModel

<form asp-controller="Raspberry" asp-action="SaveRaspberryChange" method="post">
    <div class="form-group">


        <input type="hidden" asp-for="RaspberryId" id="RaspberryId" />
        <label for="Location"><Br />Location</label>
        <input type="text" class="form-control" id="Location" asp-for="Location" />
        <label for="Name"><Br />Name</label>
        <input type="text" class="form-control" id="Name" asp-for="Name" />
        <label for="IPadress"><Br />Ip Adress</label>
        <input type="text" class="form-control" id="IPadress" asp-for="IPadress" />


    </div>

    <button type="submit" class="btn btn-info">Edit</button>


    <div asp-validation-summary="All" class="text-danger"></div>

    <form class="m-1 p-1" method="post">
    </form>

    <style>
        .input-validation-error {
            border-color: red;
        }
    </style>
</form>

Gmlu.Demo.Web/Views/Raspberry/Index.cshtml
@using Gmlu.Demo.EntityFramework.Models
@model IEnumerable<Raspberry>

<h1>Raspberry</h1>
<Br />
<a asp-action="Create">
    <button type="button" class="btn btn-success">Create</button>
</a>


<Br />
<table class="table">
    <thead>
        <tr>
            <th scope="col">IPadress</th>
            <th scope="col">location</th>
            <th scope="col">Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var raspberry in Model) 

        {
        <tr>
            <td>@raspberry.IPadress</td>
            <td>@raspberry.location</td>
            <td>@raspberry.Name</td>
            <td>
                <a asp-action="Edit" asp-route-id="@raspberry.RaspberryId">
                    <button type="button" class="btn btn-info">Edit</button>
                </a>
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@raspberry.RaspberryId">
                    <button type="button" class="btn btn-danger">Delete</button>
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>