Gmlu.Demo.Web/Models/StatsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Gmlu.Demo.EntityFramework.Models;

namespace Gmlu.Demo.Web.Models
{
    public class StatsViewModel
    {
        public StatsViewModel()
        {
            Raspberrys = new List<RaspberryStatsViewModel>();
        }

        public List<RaspberryStatsViewModel> Raspberrys { get; set; }

        public DateTime DateToFilter { get; set; }
    }

    public class RaspberryStatsViewModel
    {
        public string Name { get; set; }

        public string Id => Name.Replace(" ", string.Empty);

        public IEnumerable<MeasurePoint> MeasurePoints { get; set; }

        public string[] GetDates => MeasurePoints?.Select(x => x.Date.ToString()).ToArray();
        public decimal[] GetTemp => MeasurePoints?.Where(x => x.Temp.HasValue).Select(x => x.Temp.Value).ToArray();
        public decimal[] GetHum => MeasurePoints?.Where(x => x.Humidity.HasValue).Select(x => x.Humidity.Value).ToArray();
    }
}

Gmlu.Demo.Web/Controllers/StatsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Gmlu.Demo.Web.Models;
using Gmlu.Demo.Web.Services;
using System.Collections.Generic;
using Gmlu.Demo.EntityFramework.DataContext;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Gmlu.Demo.EntityFramework.Models;

namespace Gmlu.Demo.Web.Controllers
{
    public class StatsController : Controller
    {
        private readonly IStatsService _statsService;
        private readonly StatsContext _context;

        public StatsController(
            IStatsService statsService,
            StatsContext context)
        {
            _statsService = statsService;
            _context = context;
        }

        public IActionResult Index()
        {
            var viewModel = new StatsViewModel();

            if (!_context.Raspberrys.Any())
            {
                return RedirectToAction("Index", "Raspberry");
            }
            
            viewModel.Raspberrys = GetRaspberryStatsViewModel(
                DateTime.Now);

            viewModel.DateToFilter = DateTime.Now;

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Filter(
            StatsViewModel viewModel)
        {
            viewModel.Raspberrys = GetRaspberryStatsViewModel(
                viewModel.DateToFilter);

            return View("index", viewModel);
        }

        public List<RaspberryStatsViewModel> GetRaspberryStatsViewModel(
            DateTime filterDate)
        {
            var raspberrys = _context
               .Raspberrys
               .AsNoTracking()
               .ToList();

            var list = raspberrys
                .Select(
                    raspberry => new RaspberryStatsViewModel
                    {
                        Name = raspberry.Name,
                        MeasurePoints = _statsService
                                    .GetMeasurePoints(
                                        raspberry.RaspberryId,
                                        filterDate)
                    })
                .ToList();

            if (list.Any())
            {
                list
                    .Add(
                        new RaspberryStatsViewModel
                        {
                            Name = $"{list.First().Name}2",
                            MeasurePoints = list
                                .First()
                                .MeasurePoints
                                .Select(x => new MeasurePoint { Date = x.Date, Temp = x.Temp + 2, Humidity = x.Humidity + 2 })
                        });
            }

            if (list.Any())
            {
                list
                    .Add(
                        new RaspberryStatsViewModel
                        {
                            Name = $"{list.First().Name}3",
                            MeasurePoints = list
                                .First()
                                .MeasurePoints
                                .Select(x => new MeasurePoint { Date = x.Date, Temp = x.Temp + 1, Humidity = x.Humidity + 1 })
                        });
            }

            return list;
        }

    }
}

Gmlu.Demo.Web/Views/Stats/Index.cshtml
@using Newtonsoft.Json
@model StatsViewModel

<link href="/css/bootstrap-colorpicker.css" rel="stylesheet">


@foreach (var pi in Model.Raspberrys)
{
    <div id="div-@pi.Id">
        <h2>Color @pi.Id</h2>
        <input id="@pi.Id" type="text" />
        <p></p>
    </div>
}


<form method="post" asp-controller="Stats" asp-action="Filter">

    <div>

        <input asp-for="DateToFilter" id="date" type="text" class="form-control" />
    </div>

    <fieldset>
        <div>
            <p> </p>
            <label>&nbsp;</label>
            <input type="submit" value="Submit" class="submit" />
        </div>
    </fieldset>
</form>

<canvas id="tempChart" width="400" height="300"></canvas>
<canvas id="HumChart" width="400" height="300"></canvas>

@section Scripts {

    <script>

        $(function() {

            $("#date").datepicker({
                dateFormat: 'dd.mm.yy',
                pickTime: false,
                autoclose: true,
                forceParse: false,
                calendarWeeks: true,
                keyboardNavigation: false,
            });

            var contextTempChart = document.getElementById('tempChart').getContext('2d');
            var tempChart = new Chart(contextTempChart,
                {
                    type: 'line',
                    data: {
                        labels: @Html.Raw(JsonConvert.SerializeObject(@Model.Raspberrys.ToArray()[0].GetDates)),
                        datasets: [],
                        options: {
                            responsive: true,
                            maintainAspectRatio: false,
                            animation: {
                                duration: 0
                            },
                            hover: {
                                animationDuration: 0
                            },
                            responsiveAnimationDuration: 0
                        }
                    },
                });


            var contextHumChart = document.getElementById('HumChart').getContext('2d');
            var humChart = new Chart(contextHumChart,
                {
                    type: 'line',
                    data: {
                        labels: @Html.Raw(JsonConvert.SerializeObject(@Model.Raspberrys.ToArray()[0].GetDates)),
                        datasets: [],
                        options: {
                            responsive: true,
                            maintainAspectRatio: false,
                            animation: {
                                duration: 0
                            },
                            hover: {
                                animationDuration: 0
                            },
                            responsiveAnimationDuration: 0
                        }
                    }
                }
            );

            @foreach (var raspberry in @Model.Raspberrys)
            {
                <text>
                    var color = '#000000';

                    console.log(document.cookie);

                    if (document.cookie != null) {
                        var cookieValue1 = document.cookie
                            .split('; ')
                            .find(row => row.startsWith('@raspberry.Id' + '='))
                            .split('=')[1];

                        console.log(cookieValue1);

                        color = cookieValue1;
                    }

                    $('#@raspberry.Id').colorpicker();

                    $('#@raspberry.Id').on('colorpickerChange',
                        function(event) {
                            $('#@raspberry.Id').css('background-color', event.color.toString());

                            tempChart.data.datasets.find(x => x.label === '@raspberry.Name').borderColor = event.color.toString();
                            humChart.data.datasets.find(x => x.label === '@raspberry.Name').borderColor = event.color.toString();
                            tempChart.update();
                            humChart.update();

                            document.cookie = '@raspberry.Id' + '=' + event.color.toString();
                        });

                    var data = @Html.Raw(JsonConvert.SerializeObject(raspberry.GetTemp));

                    if (data.length > 0) {
                        tempChart.data.datasets.push({
                            label: '@raspberry.Name',
                            borderColor: color,
                            data: @Html.Raw(JsonConvert.SerializeObject(raspberry.GetTemp))
                        });
                        tempChart.update();

                        humChart.data.datasets.push({
                            label: '@raspberry.Name',
                            borderColor: color,
                            data: @Html.Raw(JsonConvert.SerializeObject(raspberry.GetHum))
                        });
                        humChart.update();

                    }
                </text>
            }
        });

    </script>
}